openapi: 3.0.0
info:
  title: E-commerce API
  version: 1.0.0
  description: REST API for managing products, orders, and users

servers:
  - url: https://api.example.com/v1
    description: Production server

tags:
  - name: Products
    description: Product catalog operations
  - name: Orders
    description: Order management
  - name: Users
    description: User account operations

paths:
  /products:
    get:
      summary: List all products
      description: Retrieve a paginated list of all products in the catalog
      operationId: listProducts
      tags:
        - Products
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          description: Number of items per page
          required: false
          schema:
            type: integer
            default: 20
            maximum: 100
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
              example:
                products:
                  - id: "prod-123"
                    name: "Wireless Headphones"
                    description: "Premium noise-cancelling wireless headphones with 30-hour battery life"
                    price: 79.99
                    category: "Electronics"
                    inStock: true
                    imageUrl: "https://example.com/images/prod-123.jpg"
                  - id: "prod-456"
                    name: "USB-C Cable"
                    description: "Durable braided USB-C to USB-C cable, 6 feet"
                    price: 12.99
                    category: "Accessories"
                    inStock: true
                    imageUrl: "https://example.com/images/prod-456.jpg"
                  - id: "prod-789"
                    name: "Laptop Stand"
                    description: "Adjustable aluminum laptop stand for ergonomic work setup"
                    price: 45.00
                    category: "Accessories"
                    inStock: true
                    imageUrl: "https://example.com/images/prod-789.jpg"
                  - id: "prod-101"
                    name: "Wireless Mouse"
                    description: "Ergonomic wireless mouse with precision tracking"
                    price: 29.99
                    category: "Electronics"
                    inStock: false
                    imageUrl: "https://example.com/images/prod-101.jpg"
                pagination:
                  currentPage: 1
                  totalPages: 5
                  totalItems: 87
                  itemsPerPage: 20

  /products/{productId}:
    get:
      summary: Get product details
      description: Retrieve detailed information about a specific product
      operationId: getProduct
      tags:
        - Products
      parameters:
        - name: productId
          in: path
          description: Unique product identifier
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Product found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
              example:
                id: "prod-123"
                name: "Wireless Headphones"
                description: "Premium noise-cancelling wireless headphones with 30-hour battery life"
                price: 79.99
                category: "Electronics"
                inStock: true
                imageUrl: "https://example.com/images/prod-123.jpg"
        '404':
          description: Product not found
          content:
            application/json:
              example:
                error: "Product not found"
                message: "The product with ID 'prod-999' does not exist"
                code: "PRODUCT_NOT_FOUND"

  /orders:
    post:
      summary: Create new order
      description: Place a new order for products
      operationId: createOrder
      tags:
        - Orders
      requestBody:
        description: Order details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateOrderRequest'
            example:
              userId: "user-123"
              items:
                - productId: "prod-456"
                  quantity: 2
                - productId: "prod-789"
                  quantity: 1
              shippingAddress:
                street: "123 Main St"
                city: "San Francisco"
                state: "CA"
                zipCode: "94102"
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
              example:
                id: "order-abc-123"
                userId: "user-123"
                items:
                  - productId: "prod-456"
                    productName: "Wireless Headphones"
                    quantity: 2
                    price: 79.99
                  - productId: "prod-789"
                    productName: "USB Cable"
                    quantity: 1
                    price: 12.99
                totalAmount: 172.97
                status: "pending"
                shippingAddress:
                  street: "123 Main St"
                  city: "San Francisco"
                  state: "CA"
                  zipCode: "94102"
                  country: "USA"
                createdAt: "2025-11-09T10:30:00Z"
                updatedAt: "2025-11-09T10:30:00Z"
        '400':
          description: Invalid order data

  /users/{userId}/orders:
    get:
      summary: Get user's orders
      description: Retrieve all orders for a specific user
      operationId: getUserOrders
      tags:
        - Orders
        - Users
      parameters:
        - name: userId
          in: path
          description: User identifier
          required: true
          schema:
            type: string
      responses:
        '200':
          description: List of user orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
              example:
                - id: "order-001"
                  userId: "user-123"
                  items:
                    - productId: "prod-456"
                      productName: "USB-C Cable"
                      quantity: 2
                      price: 12.99
                    - productId: "prod-789"
                      productName: "Laptop Stand"
                      quantity: 1
                      price: 45.00
                  totalAmount: 70.98
                  status: "delivered"
                  shippingAddress:
                    street: "123 Main St"
                    city: "San Francisco"
                    state: "CA"
                    zipCode: "94102"
                    country: "USA"
                  createdAt: "2025-11-01T10:00:00Z"
                  updatedAt: "2025-11-05T14:30:00Z"
                - id: "order-002"
                  userId: "user-123"
                  items:
                    - productId: "prod-123"
                      productName: "Wireless Headphones"
                      quantity: 1
                      price: 79.99
                  totalAmount: 79.99
                  status: "shipped"
                  shippingAddress:
                    street: "456 Oak Avenue"
                    city: "San Francisco"
                    state: "CA"
                    zipCode: "94103"
                    country: "USA"
                  createdAt: "2025-11-08T15:30:00Z"
                  updatedAt: "2025-11-09T09:00:00Z"
                - id: "order-003"
                  userId: "user-123"
                  items:
                    - productId: "prod-101"
                      productName: "Wireless Mouse"
                      quantity: 1
                      price: 29.99
                  totalAmount: 29.99
                  status: "pending"
                  shippingAddress:
                    street: "123 Main St"
                    city: "San Francisco"
                    state: "CA"
                    zipCode: "94102"
                    country: "USA"
                  createdAt: "2025-11-09T11:00:00Z"
                  updatedAt: "2025-11-09T11:00:00Z"

components:
  schemas:
    Product:
      type: object
      required:
        - id
        - name
        - price
      properties:
        id:
          type: string
          format: uuid
          description: Unique product identifier
        name:
          type: string
          description: Product name
          example: "Wireless Headphones"
        description:
          type: string
          description: Detailed product description
        price:
          type: number
          format: float
          description: Product price in USD
          example: 79.99
        category:
          type: string
          description: Product category
          example: "Electronics"
        inStock:
          type: boolean
          description: Whether product is currently in stock
          default: true
        imageUrl:
          type: string
          format: uri
          description: URL to product image

    Order:
      type: object
      required:
        - id
        - userId
        - items
        - status
        - createdAt
      properties:
        id:
          type: string
          format: uuid
          description: Unique order identifier
        userId:
          type: string
          description: ID of user who placed the order
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
        totalAmount:
          type: number
          format: float
          description: Total order amount in USD
        status:
          type: string
          enum:
            - pending
            - confirmed
            - shipped
            - delivered
            - cancelled
          description: Current order status
        shippingAddress:
          $ref: '#/components/schemas/Address'
        createdAt:
          type: string
          format: date-time
          description: Order creation timestamp
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp

    OrderItem:
      type: object
      required:
        - productId
        - quantity
        - price
      properties:
        productId:
          type: string
          description: Product identifier
        productName:
          type: string
          description: Product name at time of order
        quantity:
          type: integer
          minimum: 1
          description: Quantity ordered
        price:
          type: number
          format: float
          description: Price per unit at time of order

    CreateOrderRequest:
      type: object
      required:
        - userId
        - items
        - shippingAddress
      properties:
        userId:
          type: string
          description: User placing the order
        items:
          type: array
          minItems: 1
          items:
            type: object
            required:
              - productId
              - quantity
            properties:
              productId:
                type: string
              quantity:
                type: integer
                minimum: 1
        shippingAddress:
          $ref: '#/components/schemas/Address'

    Address:
      type: object
      required:
        - street
        - city
        - state
        - zipCode
      properties:
        street:
          type: string
          example: "123 Main St"
        city:
          type: string
          example: "San Francisco"
        state:
          type: string
          example: "CA"
        zipCode:
          type: string
          example: "94102"
        country:
          type: string
          default: "USA"

    Pagination:
      type: object
      properties:
        currentPage:
          type: integer
        totalPages:
          type: integer
        totalItems:
          type: integer
        itemsPerPage:
          type: integer
